SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[V_DV_META_LINK] AS
SELECT 
       LINK.TableName AS DV_LINK_TABLENAME,
	   ATT.[COLUMN_NAME],
	   ATT.[DV_COLUMN_NAME],
       ATT.[DATA_TYPE],
       ATT.[CHARACTER_MAXIMUM_LENGTH],
       ATT.[NUMERIC_PRECISION],
       ATT.[NUMERIC_SCALE],

       RS.RecordSourceName AS RECORDSOURCE,

       [FK]
       
FROM [META].[dbo].[ATTRIBUTE] ATT
    
    LEFT JOIN META.dbo.RecordSource RS
        ON ATT.TABLE_CATALOG = RS.DatabaseName
    LEFT JOIN META.dbo.DV_LINK LINK
        ON ATT.DV_LINK_ID = LINK.ID

WHERE LINK.TableName IS NOT NULL



GO
