SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE VIEW [gs].[V_ORDER_MTA]
AS
	SELECT LOAD_DTS,
		TODATETIMEOFFSET(
			CAST(CAST(CAST([FILE_TRANSFER_DTS] AS DATE) AS VARCHAR(10)) + ' '
				+ CAST(CAST('00:00:00' AS TIME) AS VARCHAR(16)) AS DATETIME2(7)),
			DATEDIFF(MINUTE, GETUTCDATE(), GETDATE())
		) AS LOAD_DTS_BATCH,
		ROW_NUMBER() OVER (ORDER BY CONVERT(NVARCHAR(30), [ORDERID])) AS [SEQUENCE_NO],
		CAST(NULL AS NCHAR(1)) AS CDC_OPERATION_CODE,
		'[gs]' AS [REC_SRC],
		[FULLY_QUALIFIED_FILE_NAME],
		CAST(NULL AS DATETIMEOFFSET(7)) AS [INSERT_DTS],
		CAST(NULL AS DATETIMEOFFSET(7)) AS [UPDATE_DTS],
		CAST(NULL AS DATETIMEOFFSET(7)) AS [EXPORT_DTS],
		[FILE_TRANSFER_DTS],
		SYSDATETIMEOFFSET() AS [SESSION_DTS],
		CAST(NULL AS DATETIMEOFFSET(7)) AS [SOURCE_SLICE_DTS],
		CAST('FULL' AS NVARCHAR(10)) AS [LOAD_TYPE],
		CONVERT(CHAR(32), HASHBYTES('MD5', ISNULL(TRIM(CONVERT(NVARCHAR(50), [ORDERID])+N'@|@'), N'')), 2) AS HK,
		CONVERT(
			CHAR(32),
			HASHBYTES(
				'MD5',
				+ ISNULL(TRIM(CONVERT(NVARCHAR(255), [ORDERDATE])), N'') + N'@|@'
				+ ISNULL(TRIM(CONVERT(NVARCHAR(255), [GAMEID])), N'') + N'@|@'
				+ ISNULL(TRIM(CONVERT(NVARCHAR(255), [CUSTOMERID])), N'') + N'@|@'
				),
			2
			) AS HD,
		CONVERT(
			CHAR(32),
			HASHBYTES(
				'MD5',
				+ ISNULL(TRIM(CONVERT(NVARCHAR(255), [ORDERID])), N'') + N'@|@'
				+ ISNULL(TRIM(CONVERT(NVARCHAR(255), [ORDERDATE])), N'') + N'@|@'
				+ ISNULL(TRIM(CONVERT(NVARCHAR(255), [GAMEID])), N'') + N'@|@'
				+ ISNULL(TRIM(CONVERT(NVARCHAR(255), [CUSTOMERID])), N'') + N'@|@'
				),
			2
			) AS HF,
		[ORDERID],
		[ORDERDATE],
		[GAMEID],
		[CUSTOMERID]
	FROM [gs].[ORDER];
GO
