SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [gs].[V_CUSTOMER_MTA]
AS
	SELECT CAST(NULL AS DATETIMEOFFSET(7)) AS LOAD_DTS,
		TODATETIMEOFFSET(
			CAST(CAST(CAST([FILE_TRANSFER_DTS] AS DATE) AS VARCHAR(10)) + ' '
				+ CAST(CAST('00:00:00' AS TIME) AS VARCHAR(16)) AS DATETIME2(7)),
			DATEDIFF(MINUTE, GETUTCDATE(), GETDATE())
		) AS LOAD_DTS_BATCH,
		[SEQUENCE_NO],
		CAST(NULL AS NCHAR(1)) AS CDC_OPERATION_CODE,
		[REC_SRC],
		[FULLY_QUALIFIED_FILE_NAME],
		CAST(NULL AS DATETIMEOFFSET(7)) AS [INSERT_DTS],
		CAST(NULL AS DATETIMEOFFSET(7)) AS [UPDATE_DTS],
		CAST(NULL AS DATETIMEOFFSET(7)) AS [EXPORT_DTS],
		[FILE_TRANSFER_DTS],
		[SESSION_DTS],
		CAST(NULL AS DATETIMEOFFSET(7)) AS [SOURCE_SLICE_DTS],
		CAST('FULL' AS NVARCHAR(10)) AS [LOAD_TYPE],
		CONVERT(CHAR(32), HASHBYTES('MD5', ISNULL(TRIM(CONVERT(NVARCHAR(50), [CustomerID])), N'') + N'W|D'), 2) AS HK,
		CONVERT(
			CHAR(32),
			HASHBYTES(
				'MD5',
				+ ISNULL(TRIM(CONVERT(NVARCHAR(255), [CustomerName])), N'') + N'W|D'
				+ ISNULL(TRIM(CONVERT(NVARCHAR(255), [Birth])), N'') + N'W|D'
				+ ISNULL(TRIM(CONVERT(NVARCHAR(255), [Gender])), N'') + N'W|D'
				+ ISNULL(TRIM(CONVERT(NVARCHAR(255), [Address])), N'') + N'W|D'
				),
			2
			) AS HD,
		CONVERT(
			CHAR(32),
			HASHBYTES(
				'MD5',
				ISNULL(TRIM(CONVERT(NVARCHAR(255), [CustomerID])), N'') + N'W|D'
				+ ISNULL(TRIM(CONVERT(NVARCHAR(255), [CustomerName])), N'') + N'W|D'
				+ ISNULL(TRIM(CONVERT(NVARCHAR(255), [Birth])), N'') + N'W|D'
				+ ISNULL(TRIM(CONVERT(NVARCHAR(255), [Gender])), N'') + N'W|D'
				+ ISNULL(TRIM(CONVERT(NVARCHAR(255), [Address])), N'') + N'W|D'
				),
			2
			) AS HF,
		[CustomerID],
		[CustomerName],
		[Birth],
		[Gender],
		[Address]
	FROM [gs].[CUSTOMER];
GO
