SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[USP_WRITELOG]
    @LOGMESSAGE NVARCHAR(600),
    @LOGSOURCE NVARCHAR(100),
	@MESSAGETYPE NVARCHAR(1)
AS
BEGIN

    INSERT INTO META.dbo.LOG
    (
        LOGDATE,
        LOGMESSAGE,
        LOGSOURCE,
		MESSAGETYPE
    )
    VALUES
    (   GETDATE(),   -- LOGDATE - datetime
        @LOGMESSAGE, -- LOGMESSAGE - nvarchar(600)
        @LOGSOURCE,   -- LOGSOURCE - nvarchar(100)
		@MESSAGETYPE
        );

END;
GO
