SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


/****** Script for SelectTopNRows command from SSMS  ******/

CREATE PROCEDURE [dbo].[USP_INIT_LIST]
AS
BEGIN

--TRUNCATE TABLE META.DBO.GEN_LIST

INSERT INTO META.DBO.GEN_LIST
( 
	[TABLE_CATALOG]
	,[TABLE_NAME]
	,IS_GEN
	,IS_FULLLOAD
)
SELECT DISTINCT
	[TABLE_CATALOG]
	,[TABLE_NAME]
	,0
	,1
FROM META.DBO.ATTRIBUTE
WHERE [TABLE_CATALOG]+[TABLE_NAME] NOT IN (SELECT [TABLE_CATALOG]+[TABLE_NAME] FROM META.DBO.GEN_LIST)
	  
--UPDATE [META].[dbo].[GEN_LIST] SET IS_GEN=0

END
GO
