--TRUNCATE TABLE META.DBO.ATTRIBUTE

INSERT INTO META.DBO.ATTRIBUTE
(
    TABLE_CATALOG,
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    NUMERIC_PRECISION,
    NUMERIC_SCALE
)
SELECT
    TABLE_CATALOG,
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    NUMERIC_PRECISION,
    NUMERIC_SCALE
FROM [{DBNAME}].INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('{TABLENAME}','TABLENAME')