#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generator
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="META")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClassesDataContext() : 
				base(global::Generator.Properties.Settings.Default.METAConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<RecordSource> RecordSource
		{
			get
			{
				return this.GetTable<RecordSource>();
			}
		}
		
		public System.Data.Linq.Table<V_ATTRIBUTE> V_ATTRIBUTE
		{
			get
			{
				return this.GetTable<V_ATTRIBUTE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RecordSource")]
	public partial class RecordSource
	{
		
		private int _ID;
		
		private string _RecordSourceName;
		
		private string _RecordSourceDesc;
		
		public RecordSource()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordSourceName", DbType="NVarChar(20)")]
		public string RecordSourceName
		{
			get
			{
				return this._RecordSourceName;
			}
			set
			{
				if ((this._RecordSourceName != value))
				{
					this._RecordSourceName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordSourceDesc", DbType="NVarChar(100)")]
		public string RecordSourceDesc
		{
			get
			{
				return this._RecordSourceDesc;
			}
			set
			{
				if ((this._RecordSourceDesc != value))
				{
					this._RecordSourceDesc = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_ATTRIBUTE")]
	public partial class V_ATTRIBUTE
	{
		
		private int _ID;
		
		private string _TABLE_CATALOG;
		
		private string _TABLE_NAME;
		
		private string _COLUMN_NAME;
		
		private string _DATA_TYPE;
		
		private System.Nullable<int> _CHARACTER_MAXIMUM_LENGTH;
		
		private System.Nullable<byte> _NUMERIC_PRECISION;
		
		private System.Nullable<int> _NUMERIC_SCALE;
		
		private string _RECORDSOURCE;
		
		private System.Nullable<bool> _BK;
		
		private System.Nullable<bool> _PK;
		
		private System.Nullable<bool> _DI;
		
		private System.Nullable<bool> _FK;
		
		private string _DV_SAT_TABLENAME;
		
		private string _DV_HUB_TABLENAME;
		
		private string _DV_LINK_TABLENAME;
		
		private string _DV_COLUMN_NAME;
		
		private System.Nullable<bool> _IS_FULLLOAD;
		
		public V_ATTRIBUTE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TABLE_CATALOG", DbType="NVarChar(128)")]
		public string TABLE_CATALOG
		{
			get
			{
				return this._TABLE_CATALOG;
			}
			set
			{
				if ((this._TABLE_CATALOG != value))
				{
					this._TABLE_CATALOG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TABLE_NAME", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string TABLE_NAME
		{
			get
			{
				return this._TABLE_NAME;
			}
			set
			{
				if ((this._TABLE_NAME != value))
				{
					this._TABLE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN_NAME", DbType="NVarChar(128)")]
		public string COLUMN_NAME
		{
			get
			{
				return this._COLUMN_NAME;
			}
			set
			{
				if ((this._COLUMN_NAME != value))
				{
					this._COLUMN_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_TYPE", DbType="NVarChar(128)")]
		public string DATA_TYPE
		{
			get
			{
				return this._DATA_TYPE;
			}
			set
			{
				if ((this._DATA_TYPE != value))
				{
					this._DATA_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHARACTER_MAXIMUM_LENGTH", DbType="Int")]
		public System.Nullable<int> CHARACTER_MAXIMUM_LENGTH
		{
			get
			{
				return this._CHARACTER_MAXIMUM_LENGTH;
			}
			set
			{
				if ((this._CHARACTER_MAXIMUM_LENGTH != value))
				{
					this._CHARACTER_MAXIMUM_LENGTH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMERIC_PRECISION", DbType="TinyInt")]
		public System.Nullable<byte> NUMERIC_PRECISION
		{
			get
			{
				return this._NUMERIC_PRECISION;
			}
			set
			{
				if ((this._NUMERIC_PRECISION != value))
				{
					this._NUMERIC_PRECISION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMERIC_SCALE", DbType="Int")]
		public System.Nullable<int> NUMERIC_SCALE
		{
			get
			{
				return this._NUMERIC_SCALE;
			}
			set
			{
				if ((this._NUMERIC_SCALE != value))
				{
					this._NUMERIC_SCALE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECORDSOURCE", DbType="NVarChar(20)")]
		public string RECORDSOURCE
		{
			get
			{
				return this._RECORDSOURCE;
			}
			set
			{
				if ((this._RECORDSOURCE != value))
				{
					this._RECORDSOURCE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BK", DbType="Bit")]
		public System.Nullable<bool> BK
		{
			get
			{
				return this._BK;
			}
			set
			{
				if ((this._BK != value))
				{
					this._BK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK", DbType="Bit")]
		public System.Nullable<bool> PK
		{
			get
			{
				return this._PK;
			}
			set
			{
				if ((this._PK != value))
				{
					this._PK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DI", DbType="Bit")]
		public System.Nullable<bool> DI
		{
			get
			{
				return this._DI;
			}
			set
			{
				if ((this._DI != value))
				{
					this._DI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK", DbType="Bit")]
		public System.Nullable<bool> FK
		{
			get
			{
				return this._FK;
			}
			set
			{
				if ((this._FK != value))
				{
					this._FK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DV_SAT_TABLENAME", DbType="NVarChar(50)")]
		public string DV_SAT_TABLENAME
		{
			get
			{
				return this._DV_SAT_TABLENAME;
			}
			set
			{
				if ((this._DV_SAT_TABLENAME != value))
				{
					this._DV_SAT_TABLENAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DV_HUB_TABLENAME", DbType="NVarChar(30)")]
		public string DV_HUB_TABLENAME
		{
			get
			{
				return this._DV_HUB_TABLENAME;
			}
			set
			{
				if ((this._DV_HUB_TABLENAME != value))
				{
					this._DV_HUB_TABLENAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DV_LINK_TABLENAME", DbType="NVarChar(30)")]
		public string DV_LINK_TABLENAME
		{
			get
			{
				return this._DV_LINK_TABLENAME;
			}
			set
			{
				if ((this._DV_LINK_TABLENAME != value))
				{
					this._DV_LINK_TABLENAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DV_COLUMN_NAME", DbType="NVarChar(50)")]
		public string DV_COLUMN_NAME
		{
			get
			{
				return this._DV_COLUMN_NAME;
			}
			set
			{
				if ((this._DV_COLUMN_NAME != value))
				{
					this._DV_COLUMN_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_FULLLOAD", DbType="Bit")]
		public System.Nullable<bool> IS_FULLLOAD
		{
			get
			{
				return this._IS_FULLLOAD;
			}
			set
			{
				if ((this._IS_FULLLOAD != value))
				{
					this._IS_FULLLOAD = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
