<?xml version="1.0" encoding="utf-8"?><Database Name="META" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=META;Integrated Security=True" SettingsObjectName="Generator.Properties.Settings" SettingsPropertyName="METAConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.RecordSource" Member="RecordSource">
    <Type Name="RecordSource">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RecordSourceName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="RecordSourceDesc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.V_ATTRIBUTE" Member="V_ATTRIBUTEs">
    <Type Name="V_ATTRIBUTE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TABLE_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TABLE_NAME" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="COLUMN_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="DATA_TYPE" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CHARACTER_MAXIMUM_LENGTH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NUMERIC_PRECISION" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="NUMERIC_SCALE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RECORDSOURCE" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="BK" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PK" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FK" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DV_SAT_TABLENAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DV_HUB_TABLENAME" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="DV_LINK_TABLENAME" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="DV_COLUMN_NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IS_FULLLOAD" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>