SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE PROCEDURE [gs].[USP_ORDER_LOG]
AS
	BEGIN
	DECLARE @LOGSOURCE AS NVARCHAR(100);
	SET @LOGSOURCE = N'STAGE.dbo.USP_XXX';
	
	EXEC META.dbo.USP_WRITELOG N'Start to load ORDER_LOG', @LOGSOURCE, N'N';
	
	BEGIN TRY
		BEGIN TRAN;
	
			INSERT INTO [gs].[ORDER_LOG]
			(
				[LOAD_DTS],
				[LOAD_DTS_BATCH],
				[SEQUENCE_NO],
				[CDC_OPERATION_CODE],
				[RECORD_SOURCE],
				[FULLY_QUALIFIED_FILE_NAME],
				[INSERT_DTS],
				[UPDATE_DTS],
				[EXPORT_DTS],
				[FILE_TRANSFER_DTS],
				[SESSION_DTS],
				[SOURCE_SLICE_DTS],
				[LOAD_TYPE],
				[HK],
				[HD],
				[HF],
				[ORDERID],
				[ORDERDATE],
				[GAMEID],
				[CUSTOMERID]
			)
			SELECT CDC.LOAD_DTS,
				CDC.LOAD_DTS_BATCH,
				CDC.SEQUENCE_NO,
				CDC.CDC_OPERATION_CODE,
				CDC.RECORD_SOURCE,
				CDC.FULLY_QUALIFIED_FILE_NAME,
				CDC.INSERT_DTS,
				CDC.UPDATE_DTS,
				CDC.EXPORT_DTS,
				CDC.FILE_TRANSFER_DTS,
				CDC.SESSION_DTS,
				CDC.SOURCE_SLICE_DTS,
				CDC.LOAD_TYPE AS LOAD_TYPE,
				CDC.HK AS HK,
				CDC.HD AS HD,
				CDC.HF AS HF,
				[ORDERID],
				[ORDERDATE],
				[GAMEID],
				[CUSTOMERID]
			FROM [gs].[ORDER_CDC] AS CDC
			WHERE CDC.[HF] NOT IN
			(
				SELECT [HF] FROM [gs].[ORDER_LOG]
			  );
			
			EXEC META.dbo.USP_WRITELOG N'Finish to load [gs].[ORDER_LOG]', @LOGSOURCE, N'N';
			
		COMMIT TRAN;
	END TRY
	BEGIN CATCH
	
		DECLARE @ERROR_MESSAGE AS NVARCHAR(4000);
		SET @ERROR_MESSAGE = N'Failed to load [gs].[ORDER_LOG]' + ISNULL(ERROR_MESSAGE(), '');
		EXEC META.dbo.USP_WRITELOG @ERROR_MESSAGE, @LOGSOURCE, N'E';
	END CATCH
	END;
GO
