<?xml version="1.0" encoding="utf-8"?><Database Name="META" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=META;Integrated Security=True" SettingsObjectName="CodeGenerator.Properties.Settings" SettingsPropertyName="METAConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ATTRIBUTE" Member="ATTRIBUTE">
    <Type Name="ATTRIBUTE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TABLE_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TABLE_NAME" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="COLUMN_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="DATA_TYPE" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CHARACTER_MAXIMUM_LENGTH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NUMERIC_PRECISION" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="NUMERIC_SCALE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DI" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>