CREATE TABLE [gs].[CUSTOMER]
(
[CustomerID] [ntext] COLLATE Chinese_PRC_CI_AS NULL,
[CustomerName] [ntext] COLLATE Chinese_PRC_CI_AS NULL,
[Birth] [ntext] COLLATE Chinese_PRC_CI_AS NULL,
[Gender] [ntext] COLLATE Chinese_PRC_CI_AS NULL,
[Address] [ntext] COLLATE Chinese_PRC_CI_AS NULL,
[LOAD_DTS] [datetimeoffset] NULL CONSTRAINT [DF_CUSTOMER_LOAD_DTS] DEFAULT (getdate()),
[FILE_TRANSFER_DTS] [datetimeoffset] NULL CONSTRAINT [DF_CUSTOMER_FILE_TRANSFER_DTS] DEFAULT (getdate()),
[FULLY_QUALIFIED_FILE_NAME] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF_CUSTOMER_FULLY_QUALIFIED_FILE_NAME] DEFAULT ('gs.GAME')
) ON [PRIMARY]
GO
