CREATE TABLE [gs].[ORDER]
(
[ORDERID] [int] NULL,
[ORDERDATE] [date] NULL,
[GAMEID] [int] NULL,
[CUSTOMERID] [int] NULL,
[LOAD_DTS] [datetimeoffset] NULL CONSTRAINT [DF_ORDER_LOAD_DTS] DEFAULT (getdate()),
[FILE_TRANSFER_DTS] [datetimeoffset] NULL CONSTRAINT [DF_ORDER_FILE_TRANSFER_DTS] DEFAULT (getdate()),
[FULLY_QUALIFIED_FILE_NAME] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF_ORDER_FULLY_QUALIFIED_FILE_NAME] DEFAULT (N'gs.ORDER'),
[RECORD_SOURCE] [nvarchar] (15) COLLATE Chinese_PRC_CI_AS NULL CONSTRAINT [DF_ORDER_RECORD_SOURCE] DEFAULT ('GS')
) ON [PRIMARY]
GO
