USE [master]
GO


CREATE DATABASE [CORE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Core', FILENAME = N'D:\Databases\Core.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Core_log', FILENAME = N'D:\Databases\Core_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

CREATE DATABASE [STAGE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'STAGE', FILENAME = N'D:\Databases\STAGE.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'STAGE_log', FILENAME = N'D:\Databases\STAGE_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO


USE STAGE
GO

CREATE SCHEMA [gs]
GO



USE [STAGE]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [gs].[CUSTOMER](
	[CustomerID] [int] NULL,
	[CustomerName] nvarchar(30) NULL,
	[Birth] date NULL,
	[Gender] int NULL,
	[Address] nvarchar(50) NULL,
	[LOAD_DTS] [datetimeoffset](7) NULL,
	[TRANSFER_DTS] [datetimeoffset](7) NULL,
	[REC_PATH] [nvarchar](20) NULL,
	[REC_SRC] [nvarchar](20) NULL
) ON [PRIMARY]
GO

ALTER TABLE [gs].[CUSTOMER] ADD  CONSTRAINT [DF_CUSTOMER_LOAD_DTS]  DEFAULT (getdate()) FOR [LOAD_DTS]
GO

ALTER TABLE [gs].[CUSTOMER] ADD  CONSTRAINT [DF_CUSTOMER_FILE_TRANSFER_DTS]  DEFAULT (getdate()) FOR [TRANSFER_DTS]
GO

ALTER TABLE [gs].[CUSTOMER] ADD  CONSTRAINT [DF_CUSTOMER_FULLY_QUALIFIED_FILE_NAME]  DEFAULT ('gs.GAME') FOR [REC_PATH]
GO


USE [STAGE]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [gs].[GAMELIST](
	[REC_PATH] [varchar](25) NOT NULL,
	[TRANSFER_DTS] [datetimeoffset](7) NOT NULL,
	[REC_SRC] [varchar](20) NOT NULL,
	[ID] [int] NULL,
	[Game name] [nvarchar](50) NULL,
	[AREA] [nvarchar](20) NULL,
	[PRICE] [decimal](10, 2) NULL,
	[Operator] [nvarchar](20) NULL,
	[LOAD_DTS] [datetimeoffset](7) NULL
) ON [PRIMARY]
GO

ALTER TABLE [gs].[GAMELIST] ADD  CONSTRAINT [DF_GAMELIST_Fully_Qualified_File_Name]  DEFAULT ('gs.GAME') FOR [REC_PATH]
GO

ALTER TABLE [gs].[GAMELIST] ADD  CONSTRAINT [DF_GAMELIST_FILE_TRANSFER_DTS]  DEFAULT (getdate()) FOR [TRANSFER_DTS]
GO

ALTER TABLE [gs].[GAMELIST] ADD  CONSTRAINT [DF_GAMELIST_REC_SRC]  DEFAULT ('GS') FOR [REC_SRC]
GO

ALTER TABLE [gs].[GAMELIST] ADD  CONSTRAINT [DF_GAMELIST_LOAD_DTS]  DEFAULT (getdate()) FOR [LOAD_DTS]
GO


USE [STAGE]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [gs].[ORDER](
	[ORDERID] [int] NULL,
	[ORDERDATE] [date] NULL,
	[GAMEID] [int] NULL,
	[CUSTOMERID] [int] NULL,
	[LOAD_DTS] [datetimeoffset](7) NULL,
	[TRANSFER_DTS] [datetimeoffset](7) NULL,
	[REC_PATH] [nvarchar](20) NULL,
	[REC_SRC] [nvarchar](15) NULL
) ON [PRIMARY]
GO

ALTER TABLE [gs].[ORDER] ADD  CONSTRAINT [DF_ORDER_LOAD_DTS]  DEFAULT (getdate()) FOR [LOAD_DTS]
GO

ALTER TABLE [gs].[ORDER] ADD  CONSTRAINT [DF_ORDER_FILE_TRANSFER_DTS]  DEFAULT (getdate()) FOR [TRANSFER_DTS]
GO

ALTER TABLE [gs].[ORDER] ADD  CONSTRAINT [DF_ORDER_FULLY_QUALIFIED_FILE_NAME]  DEFAULT (N'gs.ORDER') FOR [REC_PATH]
GO

ALTER TABLE [gs].[ORDER] ADD  CONSTRAINT [DF_ORDER_RECORD_SOURCE]  DEFAULT ('GS') FOR [REC_SRC]
GO


